// Generated by Citius Compiler
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#ifdef _WIN32
#include <windows.h>
#endif
#ifdef _WIN32
#include <winsock2.h>
#include <ws2tcpip.h>
#pragma comment(lib, "ws2_32.lib")
#else
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <unistd.h>
typedef int SOCKET;
#define INVALID_SOCKET (-1)
#define closesocket close
#endif
static int citius_net_inited = 0;
static void citius_net_init(void) {
  if (!citius_net_inited) {
#ifdef _WIN32
    WSADATA wsa;
    WSAStartup(MAKEWORD(2,2), &wsa);
#endif
    citius_net_inited = 1;
  }
}

static void citius_http_request(const char *host, int port,
                                const char *request, int has_headers,
                                int has_payload, int is_raw) {
  SOCKET s = socket(AF_INET, SOCK_STREAM, 0);
  if (s == INVALID_SOCKET) {
    fprintf(stderr, "socket error\n");
    return;
  }
  struct hostent *he = gethostbyname(host);
  if (!he) {
    fprintf(stderr, "host not found: %s\n", host);
    closesocket(s);
    return;
  }
  struct sockaddr_in addr;
  memset(&addr, 0, sizeof(addr));
  memcpy(&addr.sin_addr, he->h_addr_list[0], he->h_length);
  addr.sin_family = AF_INET;
  addr.sin_port = htons((short)port);
  if (connect(s, (struct sockaddr*)&addr, sizeof(addr)) != 0) {
    fprintf(stderr, "connect failed\n");
    closesocket(s);
    return;
  }
  send(s, request, strlen(request), 0);
  {
    char buf[4096];
    int n;
    while ((n = recv(s, buf, sizeof(buf) - 1, 0)) > 0) {
      buf[n] = 0;
      printf("%s", buf);
    }
  }
  closesocket(s);
}
static int64_t main(void);

static int64_t main(
void)
{
  {
    citius_net_init();
    citius_http_request("x", 1, "GET /", 0, 0, 0);
  }
}
