// Generated by Citius Compiler
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
static int64_t fib(int64_t);
static int64_t main(void);

static int64_t fib(
  int64_t n
)
{
  if ((n <= 1))
  {
    return n;
  }
  return (fib((n - 1)) + fib((n - 2)));
}

static int64_t main(
void)
{
  int64_t result = fib(20);
  printf("%lld\n", (int64_t)(result));
}
