// Generated by Citius Compiler
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
static int64_t main(void);

static int64_t main(
void)
{
  {
    int64_t i = 1;
    for (; i < 101; i++)
    {
      if (((i % 15) == 0))
      {
        printf("%s\n", "FizzBuzz\n");
      }
else       if (((i % 3) == 0))
      {
        printf("%s\n", "Fizz\n");
      }
else       if (((i % 5) == 0))
      {
        printf("%s\n", "Buzz\n");
      }
      else
      {
        printf("%lld\n", (int64_t)(i));
      }
    }
  }
}
