// Generated by Citius Compiler
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
static int64_t main(void);

static int64_t main(
void)
{
  printf("%s\n", "Hello, Citius!\n");
}
