// Generated by Citius Compiler
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
static int64_t mandelbrot(double, double);
static int64_t main(void);

static int64_t mandelbrot(
  double x,
  double y
)
{
  double cr = (y - 0.500000);
  double ci = x;
  double zi = 0.000000;
  double zr = 0.000000;
  int64_t n = 0;
  while ((n < 256))
  {
    double zr2 = (zr * zr);
    double zi2 = (zi * zi);
    if (((zr2 + zi2) > 4.000000))
    {
      return n;
    }
    (zi = (((2.000000 * zr) * zi) + ci));
    (zr = ((zr2 - zi2) + cr));
    (n = (n + 1));
  }
  return 256;
}

static int64_t main(
void)
{
  double y = (-1.000000);
  while ((y < 1.000000))
  {
    double x = (-1.500000);
    while ((x < 0.500000))
    {
      int64_t v = mandelbrot(x, y);
      if ((v > 128))
      {
        printf("%lld", (int64_t)(1));
      }
      else
      {
        printf("%lld", (int64_t)(0));
      }
      (x = (x + 0.030000));
    }
    printf("%s\n", "");
    (y = (y + 0.060000));
  }
}
