// Generated by Citius Compiler
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
static int64_t is_prime(int64_t);
static int64_t main(void);

static int64_t is_prime(
  int64_t n
)
{
  if ((n < 2))
  {
    return 0;
  }
  int64_t i = 2;
  while (((i * i) <= n))
  {
    if (((n % i) == 0))
    {
      return 0;
    }
    (i = (i + 1));
  }
  return 1;
}

static int64_t main(
void)
{
  int64_t count = 0;
  {
    int64_t i = 2;
    for (; i < 100; i++)
    {
      if (is_prime(i))
      {
        printf("%lld\n", (int64_t)(i));
        (count = (count + 1));
      }
    }
  }
  printf("%lld\n", (int64_t)(count));
}
