// Generated by Citius Compiler
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#ifdef _WIN32
#include <windows.h>
#endif
static void citius_sleep(int64_t ms) {
#ifdef _WIN32
  Sleep((DWORD)ms);
#else
  struct timespec ts;
  ts.tv_sec = ms / 1000;
  ts.tv_nsec = (long)((ms % 1000) * 1000000);
  nanosleep(&ts, NULL);
#endif
}
static int64_t main(void);

static int64_t main(
void)
{
  printf("%s\n", "Sleeping for 1 second...\n");
  citius_sleep((int64_t)(1) * 1000LL);
  printf("%s\n", "Done!\n");
  printf("%s\n", "Sleeping for 500 ms...\n");
  citius_sleep((int64_t)(500) * 1LL);
  printf("%s\n", "Done!\n");
}
